import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">LandingPage</Link>
        </li>
        <li>
          <Link to="/studentplandesktop">StudentPlanDesktop</Link>
        </li>
        <li>
          <Link to="/logindesktop">LogInDesktop</Link>
        </li>
        <li>
          <Link to="/forgetpassworddesktop">ForgetPasswordDesktop</Link>
        </li>
        <li>
          <Link to="/checkoutorder">CheckoutOrder</Link>
        </li>
        <li>
          <Link to="/checkoutordercard">CheckoutOrderCard</Link>
        </li>
        <li>
          <Link to="/checkoutorderpaypal">CheckoutOrderPaypal</Link>
        </li>
        <li>
          <Link to="/checkoutorderstripe">CheckoutOrderStripe</Link>
        </li>
        <li>
          <Link to="/checkoutorderapplepay">CheckoutOrderApplepay</Link>
        </li>
        <li>
          <Link to="/checkoutordergooglepay">CheckoutOrderGooglePay</Link>
        </li>
        <li>
          <Link to="/checkoutpending">CheckoutPending</Link>
        </li>
        <li>
          <Link to="/checkoutconfirmation">CheckoutConfirmation</Link>
        </li>
        <li>
          <Link to="/checkoutconfirmationone">CheckoutConfirmationOne</Link>
        </li>
        <li>
          <Link to="/checkoutready">CheckoutReady</Link>
        </li>
        <li>
          <Link to="/contactus">ContactUs</Link>
        </li>
        <li>
          <Link to="/studentmenu">StudentMenu</Link>
        </li>
        <li>
          <Link to="/settingsone">SettingsOne</Link>
        </li>
        <li>
          <Link to="/settingstwo">SettingsTwo</Link>
        </li>
        <li>
          <Link to="/settingsfour">SettingsFour</Link>
        </li>
        <li>
          <Link to="/settingsthree">SettingsThree</Link>
        </li>
        <li>
          <Link to="/settings">Settings</Link>
        </li>
        <li>
          <Link to="/securitycodedesktop">SecurityCodeDesktop</Link>
        </li>
        <li>
          <Link to="/newpassworddesktop">NewPasswordDesktop</Link>
        </li>
        <li>
          <Link to="/orderonline">OrderOnline</Link>
        </li>
        <li>
          <Link to="/cart">Cart</Link>
        </li>
        <li>
          <Link to="/detailsone">DetailsOne</Link>
        </li>
        <li>
          <Link to="/details">Details</Link>
        </li>
        <li>
          <Link to="/accountdesktop">AccountDesktop</Link>
        </li>
        <li>
          <Link to="/createanaccountdesktop">CreateanaccountDesktop</Link>
        </li>
        <li>
          <Link to="/personaldetailsdesktopone">PersonalDetailsDesktopOne</Link>
        </li>
        <li>
          <Link to="/personaldetailsdesktop">PersonalDetailsDesktop</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
